---
title: "Image Reconstruction CNN"
author: "Dominic Cugliari"
date: "2024-05-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```


Import our library

```{r}
library(torch)
library(luz)
library(tidymodels)
library(broom)
library(raster)
library(png)
```

```{r}
nxd <- 64
disp_scale <- 5
nrd <- ceiling(nxd * 1.42)
nphi <- nrd
```


Load in our data we need.

```{r}
ref65 <- read.csv("raw_data/65ref.csv")
ref65 <- ref65 %>% as.data.frame()
ref65 <- ref65 %>% as.matrix()
ref65 <- ref65[2:65,2:65]
refimg <- ref65 %>% image()

```




```{r}
reftorch <- torch_tensor(ref65)$unsqueeze(1)
reftorch <- reftorch$unsqueeze(1)
reftorch <- reftorch$float()
```

Create the torch system matrix



```{r}
#yptest <- matrix(0, nxd, nphi)

#yp_count <- integer(10000)
#bin_count <- integer(10000)
#count <- 0

#make_torch_system_matrix <- function(nxd, nrd, nphi) {
  #system_matrix <- torch_zeros(nrd*nphi, nxd*nxd);
      #for (xv in 1:nxd) { 
        #for (yv in 1:nxd){
            #for (ph in 1:nphi){
               # yp <- -(xv-(nxd*0.5)) * sin(ph*pi/nphi)+(yv-(nxd*0.5)) * cos(ph*pi/nphi);
               # count <- count+1;
               # yp_count[count] <- yp;
               # yp_bin <- as.integer(yp+nrd/2);
               # bin_count[count]<- yp_bin;
               # system_matrix[yp_bin + ph*nrd, xv + yv*nxd] = 1;
           # }
       # }
     # }
      #return(system_matrix, yp_count, bin_count);
   # }

make_torch_system_matrix <- function(nxd, nrd, nphi) {
  system_matrix <- torch_zeros(nrd * nphi, nxd * nxd)
  for (xv in 1:nxd) {
    for (yv in 1:nxd) {
      for (ph in 1:nphi) {
        yp <- -(xv - (nxd * 0.5)) * sin(ph * pi / nphi) + (yv - (nxd * 0.5)) * cos(ph * pi / nphi)
        yp_bin <- as.integer(yp + nrd / 2)
        system_matrix[yp_bin + ph * nrd, xv + yv * nxd] = 1.0
      }
    }
  }
  return(system_matrix)
}

```

Create a forward projection function

```{r}
fp_system_torch <- function(image, sys_mat, nxd, nrd, nphi) {
  fp <- torch_reshape(image, c(nxd*nxd,1));
  fb <- torch_mm(sys_mat, fp);
  return(torch_reshape(fb, c(nphi,nrd)));
  
  }
```

Create a back projection function

```{r}
bp_system_torch <- function(sino, sys_mat, nxd, nrd, nphi) {
   return(torch_reshape(torch_mm(sys_mat.T, torch_reshape(sino, c(nrd*nphi,1))), c(nxd,nxd)))
}

```

Make the sys_mat

```{r}
t <- make_torch_system_matrix(nxd, nrd, nphi)
t
```

```{r}
s <- fp_system_torch(reftorch, t, nxd, nrd, nphi)

sino <- s$squeeze(1)
sino<- sino$squeeze(1)
true_sinogram_torch <- s

sino <- sino %>% as.matrix()
image(sino)
```

Let's create a CNN Module

```{r}
set.seed(777)
torch_manual_seed(777)

convnet <- nn_module(
  "convnet",
  
  inititalize = function() {
    self$conv1 <- nn_conv2d(1, 5, 3)
    self$conv2 <- nn_conv2d(5, 10, 3)
    self$conv3 <- nn_conv2d(10, 20, 3)
    
    self$output <- nn_linear(20, 1, 3)
  },
  
  forward = function(x) {
    x %>%
      self$conv1() %>%
      nnf_relu() %>%
      nnf_max_pool2d(2) %>%
      self$conv2() %>%
      nnf_relu() %>%
      nnf_max_pool2d(2) %>%
      self$conv3() %>%
      nnf_relu() %>%
      nnf_max_pool2d(2) %>%
      torch_flatten(start_dim = 2) %>%
      self$output()
  }
)

cnn <- convnet()
```

Create an FBP CNN Module

```{r}
FBP_CNN_Net <- function(cnn, sino_for_reconstruction) {
  sens_image <- bp_system_torch(torch$ones_like(sino_for_reconstruction), sys_mat, nxd, nrd, nphi)
  
  forward <- function(sino_for_reconstruction) {
    filtered_sino <- cnn(sino_for_reconstruction)
    recon <- bp_system_torch(filtered_sino, sys_mat, nxd, nrd, nphi) / (sens_image + 1.0e-15)
    recon <- prelu(recon)
    fpsino <- fp_system_torch(recon, sys_mat, nxd, nrd, nphi)
    
    return(list(recon, fpsino, filtered_sino))
  }
  
  return(list(forward = forward))
}

fbpnet <- FBP_CNN_Net(cnn, true_sinogram_torch)

```








