---
title: "SO-ANN2"
author: "Sydney Olander"
date: "2024-06-10"
output: html_document
---

## Create working directory
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir=normalizePath(".."))
```

## Load libraries
```{r}
library(neuralnet)
library(tidyverse)
library(binhf)
library(Matrix)
library(ggplot2)
library(pracma)
library(OpenImageR)
```

## Read in data 
```{r}
# read in reference data
m <- read_csv("raw_data/SO-pic.csv")
m <- m[, -c(1)]

# Replace 0.001 with 0
for(x in 1:ncol(m)){
  for(y in 1:nrow(m)){
    if(m[x,y]==0.001)
      m[x,y] <- 0
  }
}

v <- matrix(nrow = 3, ncol = 0)
# Populate 'v' with columns, rows, and values from 'm'
for (i in 1:nrow(m)){
  for (j in 1:ncol(m)){
    v <- cbind(v, c(i,j,m[i,j]))
  }
}

# Create empty vectors `x`, `z`, and 'output'
x <- vector(length = 0) 
z <- vector(length = 0)
output <- vector(length = 0)

# Extract values from each row of `v`
for (i in 1:ncol(v)){ 
     x <- c(x, v[2, i])
     z <- c(z, v[1, i])
     output <- c(output, v[3, i]) 
}
xv<- as.vector(as.numeric(x))
zv<- as.vector(as.numeric(z))
xv <- (xv-(max(xv)+1)/2) # make x and z correct for the shift flip sum code
zv <- -1*(zv-(max(zv)+1)/2) # origin referenced coordinates  
```


## Train neural net
```{r}
# read in sinogram data
sino <- read.csv('raw_data/SO-sinogram.csv')
ranges <- sino[,c(1)]
sino <- sino[, -c(1)]
# number of projections
nAngle  <- nrow(sino)
# number of detectors
nDetect <- ncol(sino)
# Degrees between projections
angleStep <- 180/(nAngle) # changed from nAngle-1
# compute angle of each projection in sinogram
degree <- data.frame(angle = seq(0,nAngle-1)*angleStep) 

# initialize weights
nn <- list()
nn$weights <- list()

set.seed(222) 
nn$weights[[1]] <- matrix(runif(1,min=0,max=3), nrow = 91, ncol = 4)
nn$weights[[2]] <- matrix(runif(1,min=0,max=3), nrow = 5, ncol = 1)
error <- matrix(nrow = 1, ncol = 0)
for (i in 1:length(output)){
  # compute shift of sinogram detector positions for each projection based on current image pixel
  degree$pixel <- round(xv[i]*cos(pi*degree$angle/180) + zv[i]*sin(pi*degree$angle/180))
  # create a space with dimension sino
  ssino <- sino   
  ######################################################## SHIFT SUM FLIP 
  # Perform shift according to degree$pixel
  for (j in 1:nAngle){ 
    shift_amount <- 0 - degree$pixel[j]
    shifted_row <- circshift(as.vector(sino[j, ]), shift_amount)
    ssino[j, ] <- shifted_row
  }
  # perform summation
  f_vector <- colSums(ssino) 
  # perform flip
  z_vector <- rev(f_vector)  
   
  ################################################################## DATA
  data <- t(as_tibble(c(unlist(z_vector, use.names=FALSE), unlist(output[i],use.names=FALSE))))
  # Define names of the columns for the data to used by function 
  ANN_names <- c(paste0("z",(as.character(c(seq(1:nDetect))))),"o") 
  colnames(data) <- ANN_names
  ############################################################### FORMULA
  f <- as.formula(paste(ANN_names[nDetect+1],
                       "~",
                       paste(ANN_names[!ANN_names %in% "o"], collapse = " + ")
                       )
                 ) 
  ############################################################ NEURAL NET
  nn <-neuralnet(f, data, hidden = 2,
                startweights = nn$weights)
  error[i] <- nn$result.matrix[1]
  #if(error[i]==min(error)){
    #m1 <- nn$weights[[1]][[1]]
    #m2 <- nn$weights[[1]][[2]]
    #m1 <- m1 %>% as.data.frame()
    #m2 <- m2 %>% as.data.frame()
  #}
  print(i)
}

# Creating matrices 'm1' which contains the weights from the first layer and 'm2' which contains the
# weights from the second layer
m1 <- nn$weights[[1]][[1]]
m2 <- nn$weights[[1]][[2]]
m1 <- m1 %>% as.data.frame()
m2 <- m2 %>% as.data.frame()


```



```{r}
filt_sinoA <- sino
filt_sinoB <- sino
#filt_sinoC <- sino
#filt_sinoD <- sino
nRows <- nrow(sino)

for(val in 1:nRows){
  for(s in 1:length(sino[val,])){
    filt_sinoA[val,s] <- m1[1+val,1]*sino[val,s]
  }
}

filt_sinoA %>% 
  as.matrix()

write_csv(filt_sinoA, "raw_data/filtsinoa-SO.csv")


for(val in 1:nRows){
  for(s in 1:length(sino[val,])){
    filt_sinoB[val,s] <- m1[1+val,2]*sino[val,s]
  }
}

filt_sinoB %>% 
  as.matrix()

write_csv(filt_sinoB, "raw_data/filtsinob-SO.csv")

#for(val in 1:nRows){
 # for(s in 1:length(sino[val,])){
 #   filt_sinoC[val,s] <- m1[1+val,3]*sino[val,s]
#  }
#}

#filt_sinoC %>% 
 # as.matrix()

#write_csv(filt_sinoC, "raw_data/filtsinoc-SO.csv")


write_csv(m1, "raw_data/m1-SO.csv")
write_csv(m2, "raw_data/m2-SO.csv")

```

##Convolve function version
```{r}
filt_sinoA <- sino
filt_sinoB <- sino
number_cols <- ncol(sino)

for(val in 1:number_cols){
                    filt_sinoA[,val] <- convolve(sino[,val], m1[1:91,1], type ="circular")
}

filt_sinoA %>% 
  as.matrix()

write_csv(filt_sinoA, "raw_data/filtsinoa2-SO.csv")


for(val in 1:number_cols){
                   filt_sinoB[,val] <- convolve(sino[,val], m1[1:91,2], type ="circular")
}

filt_sinoB %>% 
  as.matrix()

write_csv(filt_sinoB, "raw_data/filtsinob2-SO.csv")

write_csv(m1, "raw_data/m1-SO-2.csv")
write_csv(m2, "raw_data/m2-SO-2.csv")
```

## Read in the FBP image!!!
```{r}
 p <- read.csv("clean_data/FBP1-SO.csv")
p <- p %>% as.matrix()
p <- p[,-1]
image(p)
```

